---
apiVersion: v1
kind: Service
metadata:
  name: gatlingsolr
  namespace: namespace_filler
  labels:
    app: gatlingsolr
spec:
  ports:
  - port: 80
    name: gatlingsolr
  clusterIP: None
  selector:
    app: gatlingsolr
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gatlingsolr
  namespace: namespace_filler
spec:
  selector:
    matchLabels:
      app: gatlingsolr # has to match .spec.template.metadata.labels
  serviceName: "gatlingsolr"
  replicas: gatling-nodes-replicas
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: gatlingsolr # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: gatlingsolr
        image: sarkaramrit2/gatling-solr:latest
        ports:
        - containerPort: 80
          name: gatlingsolr
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OAUTH2_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: "oauth2"
                key: oauth2-client-id
          - name: OAUTH2_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "oauth2"
                key: oauth2-client-secret